// <auto-generated />
using System;
using Chamedoon.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chamedoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130063716_migrationsname")]
    partial class migrationsname
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chamedoon.Domin.Entity.Blogs.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArticleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("VisitCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Blogs.ArticleComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<long>("ArticleId1")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReaedAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<long>("UserId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId1");

                    b.HasIndex("UserId1");

                    b.ToTable("ArticleComment");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Countries.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InvestmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvestmentCurrency")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InvestmentNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MaritalStatusImpact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AdditionalInfo = "طبق داده‌های رسمی بازار کار کانادا، نرخ بیکاری ۶٫۹ درصد است، جمعیت شاغل ۲۲٬۶۳۹٬۱۰۰ نفر و میانگین درآمد هفتگی ۱٬۳۱۲ دلار است؛ همچنین ۵۰۵٬۸۷۵ موقعیت شغلی خالی گزارش شده است【514275740625177†L129-L137】. این ارقام نشان می‌دهد بازار کار کانادا پویا و دارای فرصت‌های فراوان است و منابع رسمی به افراد برای برنامه‌ریزی شغلی کمک می‌کنند【514275740625177†L140-L155】. سیستم آموزش عالی کانادا از بهترین‌های جهان بوده و سرمایه‌گذاری زیادی در پژوهش و فناوری انجام می‌شود؛ اقتصاد کشور عمدتاً مبتنی بر خدمات و منابع طبیعی بوده و سرانهٔ تولید ناخالص داخلی بالاست.",
                            InvestmentAmount = 75000m,
                            InvestmentCurrency = "دلار کانادا",
                            InvestmentNotes = "برای دریافت ویزای استارت‌آپ کانادا باید حداقل ۲۰۰٬۰۰۰ دلار کانادا از یک صندوق سرمایه‌گذاری خطرپذیر یا ۷۵٬۰۰۰ دلار کانادا از یک گروه سرمایه‌گذار فرشته جذب شود؛ در صورت پذیرش توسط انکوباتور تجاری، نیازی به سرمایه اولیه نیست.",
                            IsDeleted = false,
                            Key = "Canada",
                            MaritalStatusImpact = "در سیستم امتیازدهی اکسپرس انتری کانادا، مجردها امتیاز کامل دریافت می‌کنند و افراد متأهل به دلیل تقسیم امتیازات انسانی (سن، تحصیلات، زبان، سابقه کار) با همسر امتیاز کمتری می‌گیرند؛ با این حال امتیازات تحصیلات و زبان همسر می‌تواند اختلاف را جبران کند【791007699362788†L87-L106】.",
                            Name = "کانادا"
                        },
                        new
                        {
                            Id = 2L,
                            AdditionalInfo = "در ژوئن ۲۰۲۵، نرخ بیکاری استرالیا ۴٫۲ درصد، نرخ اشتغال ۶۴٫۲ درصد و نرخ مشارکت نیروی کار ۶۷ درصد بود【786682023731967†L230-L237】. این نشان می‌دهد بازار کار استرالیا نسبتاً قوی است هرچند کمبود نیروی کار در حوزه‌های تکنسین و متخصص وجود دارد【101680514043225†L790-L801】. سیستم آموزشی استرالیا کیفیت بالایی دارد و دانشگاه‌های این کشور در رده‌بندی جهانی جایگاه خوبی دارند. اقتصاد کشور بر پایهٔ خدمات، معدن و کشاورزی است و سطح زندگی بالا است.",
                            InvestmentAmount = 2500000m,
                            InvestmentCurrency = "دلار استرالیا",
                            InvestmentNotes = "برنامهٔ Investor stream (ساب کلاس ۱۸۸) در ۳۱ ژوئیهٔ ۲۰۲۴ بسته شد؛ پیش از آن متقاضیان باید حداقل ۲٫۵ میلیون دلار استرالیا سرمایه‌گذاری کرده و توسط یک ایالت یا قلمرو نامزد می‌شدند.",
                            IsDeleted = false,
                            Key = "Australia",
                            MaritalStatusImpact = "در ویزای مهارت استرالیا، مجرد بودن یا داشتن همسر شهروند یا دارندهٔ اقامت دائم ۱۰ امتیاز اضافی می‌دهد و اگر همسر دارای مهارت حرفه‌ای و زبان انگلیسی مناسب باشد نیز امتیاز کمتری (۵) داده می‌شود؛ در غیر این صورت امتیازی در این بخش دریافت نمی‌شود【809286149497200†L110-L147】.",
                            Name = "استرالیا"
                        },
                        new
                        {
                            Id = 3L,
                            AdditionalInfo = "اقتصاد آلمان از پیشروترین اقتصادهای جهان است و صنایع خودرو، مهندسی و فناوری اطلاعات در آن نقش اساسی دارند. سایت «Make it in Germany» اعلام کرده است که شرکت‌های آلمانی به دلیل انقلاب صنعتی ۴٫۰ به دنبال متخصصان فناوری اطلاعات و مهندسان هستند و در این رشته‌ها کمبود نیروی متخصص وجود دارد【538120821009572†L329-L343】. همچنین در علوم و پژوهش نیز کمبود نیروی متخصص دیده می‌شود【538120821009572†L351-L353】. دانشگاه‌های آلمان استانداردهای آموزشی بالا دارند و بسیاری از دوره‌ها به زبان انگلیسی ارائه می‌شوند. نرخ بیکاری نسبتاً پایین و سطح دستمزدها بالا است.",
                            InvestmentAmount = 0m,
                            InvestmentCurrency = "یورو",
                            InvestmentNotes = "برای دریافت اجازهٔ اقامت خوداشتغالی در آلمان، حداقل سرمایه مشخصی تعیین نشده است. متقاضی باید نشان دهد که طرح تجاری او برای اقتصاد منطقه مفید است و هزینه‌های طرح و زندگی خود را تامین کرده و دارای بیمه و بازنشستگی کافی است.",
                            IsDeleted = false,
                            Key = "Germany",
                            MaritalStatusImpact = "در برنامهٔ کارت فرصت آلمان، داشتن همسر که شرایط تحصیلی و زبانی را داشته باشد یک امتیاز اضافی می‌دهد و مجرد بودن موجب تقسیم امتیاز نمی‌شود؛ در سایر برنامه‌ها وضعیت تأهل نقش مستقیمی در امتیاز ندارد【270736592507908†L399-L411】.",
                            Name = "آلمان"
                        },
                        new
                        {
                            Id = 4L,
                            AdditionalInfo = "طبق گزارش وضعیت اشتغال ماه سپتامبر ۲۰۲۵، نرخ بیکاری آمریکا ۴٫۴ درصد و تعداد افراد بیکار ۷٫۶ میلیون نفر بوده و میانگین دستمزد ساعتی ۳۶٫۶۷ دلار است【539452480876108†L327-L336】【539452480876108†L421-L427】. نرخ مشارکت نیروی کار در حدود ۶۲٫۴ درصد است و اقتصاد آمریکا با تولید ناخالص داخلی بالا به‌عنوان بزرگ‌ترین اقتصاد جهان شناخته می‌شود. دانشگاه‌های ایالات متحده در رتبه‌بندی جهانی جایگاه بالایی دارند و منابع مالی پژوهشی فراوانی در اختیار دارند.",
                            InvestmentAmount = 800000m,
                            InvestmentCurrency = "دلار آمریکا",
                            InvestmentNotes = "برای دریافت ویزای EB‑5 باید حداقل ۱٬۰۵۰٬۰۰۰ دلار آمریکا در یک کسب‌وکار جدید سرمایه‌گذاری کرده و ده شغل تمام‌وقت ایجاد کنید؛ اگر سرمایه‌گذاری در منطقهٔ بیکاری بالا یا روستایی (TEA) انجام شود، حداقل سرمایه ۸۰۰٬۰۰۰ دلار است.",
                            IsDeleted = false,
                            Key = "USA",
                            MaritalStatusImpact = "مجرد یا متأهل بودن در سیستم‌های مهاجرتی آمریکا تأثیر مستقیمی بر امتیاز ندارد؛ تنها برای ویزاهای خانوادگی مانند ازدواج با شهروند یا مقیم دائم مزیت محسوب می‌شود.",
                            Name = "ایالات متحده آمریکا"
                        },
                        new
                        {
                            Id = 5L,
                            AdditionalInfo = "طبق گزارش EURES، در هلند کمبود نیروی کار در حوزه‌های مدیریت و بازرگانی، ساختمان و رشته‌های علوم و مهندسی وجود دارد و بخش‌های بهداشت، آموزش، هنر و فناوری اطلاعات بیشترین نرخ خالی بودن شغل را دارند【394404756887990†L194-L222】. اقتصاد هلند به شدت باز و مبتنی بر تجارت و خدمات است و دانشگاه‌های هلند دوره‌های بسیاری را به زبان انگلیسی برگزار می‌کنند. نرخ بیکاری پایین و سطح رفاه اجتماعی بالا است.",
                            InvestmentAmount = 1250000m,
                            InvestmentCurrency = "یورو",
                            InvestmentNotes = "برنامهٔ پذیرش سرمایه‌گذار خارجی هلند در ۱۷ آوریل ۲۰۲۴ لغو شد؛ پیش از آن متقاضیان باید حداقل ۱٫۲۵ میلیون یورو در یک شرکت نوآور هلندی سرمایه‌گذاری می‌کردند. در حال حاضر دریافت اقامت از طریق این برنامه ممکن نیست.",
                            IsDeleted = false,
                            Key = "Netherlands",
                            MaritalStatusImpact = "در سیستم مهاجرتی هلند، مجرد یا متأهل بودن امتیازی ایجاد نمی‌کند و تنها در ویزاهای پیوست همسر و خانواده اهمیت دارد.",
                            Name = "هلند"
                        },
                        new
                        {
                            Id = 6L,
                            AdditionalInfo = "گزارش Cedefop نشان می‌دهد که اسپانیا با کمبود قابل توجهی در حوزهٔ متخصصان ICT و توسعه‌دهندگان نرم‌افزار مواجه است؛ دیجیتال‌سازی گسترده و تقاضای بالا علت این کمبود است【189557896059467†L342-L375】. همچنین تقاضا برای مهندسان و متخصصان تولید زیاد است و عرضهٔ نیروی کار در این رشته‌ها کافی نیست【189557896059467†L408-L433】. اقتصاد اسپانیا عمدتاً بر خدمات و گردشگری استوار است و نرخ بیکاری به‌ویژه در بین جوانان بالاست. دانشگاه‌های اسپانیا در رشته‌های علوم انسانی و هنر شناخته شده‌اند ولی بودجهٔ پژوهشی نسبت به برخی کشورهای اروپایی کمتر است.",
                            InvestmentAmount = 500000m,
                            InvestmentCurrency = "یورو",
                            InvestmentNotes = "بر اساس قانون ۱۴/۲۰۱۳، سرمایه‌گذاران می‌توانستند با ۲ میلیون یورو سرمایه‌گذاری در اوراق قرضه دولتی، ۱ میلیون یورو در سهام یا صندوق‌ها، یا خرید ملک به ارزش حداقل ۵۰۰ هزار یورو، ویزای طلایی اسپانیا دریافت کنند. این برنامه قرار است در سال ۲۰۲۵ خاتمه یابد.",
                            IsDeleted = false,
                            Key = "Spain",
                            MaritalStatusImpact = "اسپانیا سیستم امتیازدهی برای مهاجرت ندارد و مجرد یا متأهل بودن در امتیاز نقشی ندارد؛ تنها در ویزاهای پیوست خانواده مؤثر است.",
                            Name = "اسپانیا"
                        },
                        new
                        {
                            Id = 7L,
                            AdditionalInfo = "آمارهای رسمی نشان می‌دهند که در سپتامبر ۲۰۲۵ نرخ بیکاری سوئد ۸٫۳ درصد (۸٫۷ درصد با تعدیل فصلی) و نرخ اشتغال ۶۸٫۹ درصد و نرخ مشارکت نیروی کار ۷۵٫۵ درصد بوده است【32727063083057†L36-L55】【32727063083057†L52-L57】. این نشان‌دهندهٔ بازاری کار نسبتاً پایدار اما با بیکاری بالاتر از میانگین برخی کشورهای اروپایی است. سوئد با کمبود نیرو در حوزه‌های پزشکی، مهندسی و فناوری مواجه است و برای این مشاغل فهرست کمبود وجود دارد. سیستم آموزشی رایگان و با کیفیت بالا بوده و اقتصاد بر پایهٔ فناوری، خدمات و صنایع صادراتی مانند فناوری اطلاعات، خودرو و دارو استوار است.",
                            InvestmentAmount = 200000m,
                            InvestmentCurrency = "کرون سوئد",
                            InvestmentNotes = "برای ویزای خوداشتغالی سوئد باید نشان دهید حداقل ۲۰۰٬۰۰۰ کرون برای خود، ۱۰۰٬۰۰۰ کرون برای همسر و ۵۰٬۰۰۰ کرون برای هر فرزند برای دو سال اول زندگی در اختیار دارید و همچنین سرمایه لازم برای خرید یا راه‌اندازی کسب‌وکار را فراهم کنید.",
                            IsDeleted = false,
                            Key = "Sweden",
                            MaritalStatusImpact = "در برنامه‌های مهاجرتی سوئد، مجرد یا متأهل بودن امتیاز جداگانه‌ای ایجاد نمی‌کند؛ تنها برای پیوست همسر و فرزندان اهمیت دارد.",
                            Name = "سوئد"
                        },
                        new
                        {
                            Id = 8L,
                            AdditionalInfo = "گزارش Cedefop نشان می‌دهد که ایتالیا در مشاغل فناوری اطلاعات، توسعه‌دهندگان نرم‌افزار، ریاضیدانان و مهندسان الکترونیک با کمبود شدید نیرو مواجه است، زیرا تولید فارغ‌التحصیلان کافی نیست و تقاضا بالاست【982764113348400†L342-L378】. همچنین در حوزه‌های STEM و سلامت کمبود نیرو وجود دارد و تقاضا برای کارکنان سلامت هر سال حدود ۲ درصد افزایش می‌یابد【982764113348400†L408-L452】. اقتصاد ایتالیا بر پایهٔ تولید صنعتی و گردشگری استوار است و نرخ بیکاری جوانان نسبتاً بالاست. دانشگاه‌های این کشور به‌ویژه در رشته‌های مهندسی، طراحی و هنر شهرت دارند.",
                            InvestmentAmount = 250000m,
                            InvestmentCurrency = "یورو",
                            InvestmentNotes = "برای دریافت ویزای سرمایه‌گذاری ایتالیا باید یکی از گزینه‌های زیر را انتخاب کنید: ۲ میلیون یورو سرمایه‌گذاری در اوراق قرضه دولتی، ۵۰۰ هزار یورو در یک شرکت ایتالیایی، ۲۵۰ هزار یورو در یک استارتاپ نوآور یا ۱ میلیون یورو کمک به یک پروژهٔ خیریه.",
                            IsDeleted = false,
                            Key = "Italy",
                            MaritalStatusImpact = "در برنامه‌های مهاجرتی ایتالیا وضعیت تأهل تأثیر مستقیمی بر امتیاز ندارد و صرفاً در ویزاهای پیوست خانواده و الحاق همسر اهمیت پیدا می‌کند.",
                            Name = "ایتالیا"
                        },
                        new
                        {
                            Id = 9L,
                            AdditionalInfo = "عمان در چارچوب چشم‌انداز ۲۰۴۰ به‌دنبال تنوع‌بخشی به اقتصاد و آموزش مهارت‌های دیجیتال است و دولت برای توسعهٔ زیرساخت‌ها و صنایع غیرنفتی سرمایه‌گذاری می‌کند؛ گزارش‌ها نشان می‌دهد رشد اشتغال در سال ۲۰۲۴ حدود ۱۰٫۶ درصد بوده و تمرکز بر آموزش نیروهای عمانی در صنایع نوظهور است【107658387508375†L67-L100】. اقتصاد عمان همچنان به نفت وابسته است اما پروژه‌های بزرگ صنعتی و گردشگری در حال توسعه‌اند. نظام آموزشی در حال ارتقا است هرچند بسیاری از متخصصان برای تحصیلات عالی به خارج می‌روند. سیاست عمانیزه کردن سبب محدودیت برای استخدام خارجی‌ها شده است.",
                            InvestmentAmount = 200000m,
                            InvestmentCurrency = "ریال عمانی",
                            InvestmentNotes = "برای دریافت ویزای سرمایه‌گذاری ۵ یا ۱۰ ساله عمان، متقاضی باید از طریق وزارت تجارت درخواست دهد و هزینهٔ صدور به ترتیب ۲۵۰ و ۵۰۰ ریال عمانی است. برای اقامت طلایی، سرمایه‌گذاری حداقل ۲۰۰٬۰۰۰ ریال عمانی از طریق خرید ملک، اوراق قرضه یا ایجاد اشتغال برای ۵۰ نفر لازم است.",
                            IsDeleted = false,
                            Key = "Oman",
                            MaritalStatusImpact = "در برنامهٔ اقامت سرمایه‌گذاری عمان، مجرد یا متأهل بودن امتیاز جداگانه‌ای ایجاد نمی‌کند؛ همسر و فرزندان می‌توانند به عنوان همراه درخواست دهند، اما امتیاز خاصی اضافه نمی‌شود.",
                            Name = "عمان"
                        },
                        new
                        {
                            Id = 10L,
                            AdditionalInfo = "بازار کار هند به‌سرعت در حوزه‌های فناوری، هوش مصنوعی و یادگیری ماشین رشد می‌کند و براساس گزارش مجمع جهانی اقتصاد، دو سوم شرکت‌ها قصد دارند نیروی متخصص فناوری را افزایش دهند؛ اما شکاف مهارتی و نیاز به بازآموزی وجود دارد【565810706922104†L20-L77】. اقتصاد هند با رشد ۶ تا ۷ درصدی یکی از سریع‌ترین اقتصادهای جهان است، ولی بیکاری جوانان و نابرابری درآمدی همچنان چالش‌برانگیز است. نظام آموزشی بسیار وسیع بوده و دانشگاه‌های معتبر بسیاری در حوزه‌های مهندسی و فناوری وجود دارد، هرچند کیفیت در میان مؤسسات متفاوت است.",
                            InvestmentAmount = 100000000m,
                            InvestmentCurrency = "روپیه هند",
                            InvestmentNotes = "برای دریافت وضعیت اقامت دائم (Permanent Residency Status) باید حداقل ۱۰ کرور روپیه ظرف ۱۸ ماه یا ۲۵ کرور روپیه ظرف ۳۶ ماه سرمایه‌گذاری کنید و حداقل برای ۲۰ نفر کار ایجاد کنید.",
                            IsDeleted = false,
                            Key = "India",
                            MaritalStatusImpact = "وضعیت تأهل در فرآیند مهاجرت به هند نقش مستقیمی ندارد؛ افراد متأهل می‌توانند همسر و فرزندان خود را به‌عنوان وابسته همراه داشته باشند و برایشان ویزای همراه صادر می‌شود. مهم‌ترین شرط، احراز شرایط سرمایه‌گذاری و سایر الزامات قانونی است.",
                            Name = "هند"
                        });
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Countries.CountryLivingCost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryLivingCosts");

                    b.HasData(
                        new
                        {
                            Id = 1001L,
                            CountryId = 1L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۵٬۲۲۴٫۱ دلار کانادا ≈ ۳٬۷۳۸ دلار آمریکا"
                        },
                        new
                        {
                            Id = 1002L,
                            CountryId = 1L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۱٬۴۳۲٫۷ دلار کانادا ≈ ۱٬۰۲۵ دلار آمریکا"
                        },
                        new
                        {
                            Id = 1003L,
                            CountryId = 1L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه حدود ۱۰۴٫۵ C$ (≈۷۴٫۸ $)"
                        },
                        new
                        {
                            Id = 1004L,
                            CountryId = 1L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب و گاز برای آپارتمان ۸۵ مترمربع: حدود ۲۰۸٫۷۸ C$ (≈۱۴۹٫۴ $)"
                        },
                        new
                        {
                            Id = 1005L,
                            CountryId = 1L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ۵۹٫۰۱ C$ (≈۴۲٫۲ $) و بلیط سینما ۱۵٫۸۲ C$ (≈۱۱٫۳ $)"
                        },
                        new
                        {
                            Id = 1006L,
                            CountryId = 1L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در سه شهر بزرگ: ≈ ۲٬۲۵۱ C$ (≈۱٬۶۱۱ $)"
                        },
                        new
                        {
                            Id = 1007L,
                            CountryId = 1L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر بزرگ: ≈ ۳٬۸۴۱ C$ (≈۲٬۷۴۹ $)"
                        },
                        new
                        {
                            Id = 1008L,
                            CountryId = 1L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: حدود ۸۵٫۶۱ C$ (≈۶۱٫۳ $) در ماه"
                        },
                        new
                        {
                            Id = 2001L,
                            CountryId = 2L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۵٬۶۹۴٫۵ دلار استرالیا ≈ ۳٬۷۳۲ دلار آمریکا"
                        },
                        new
                        {
                            Id = 2002L,
                            CountryId = 2L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۱٬۵۸۰٫۵ دلار استرالیا ≈ ۱٬۰۳۶ دلار آمریکا"
                        },
                        new
                        {
                            Id = 2003L,
                            CountryId = 2L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه حدود ۱۴۰ A$ (≈۹۱٫۸ $)"
                        },
                        new
                        {
                            Id = 2004L,
                            CountryId = 2L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب، گاز و زباله برای آپارتمان ۸۵ مترمربع: حدود ۲۷۴٫۴۲ A$ (≈۱۷۹٫۹ $)"
                        },
                        new
                        {
                            Id = 2005L,
                            CountryId = 2L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ≈ ۷۳ A$ (≈۴۷٫۸ $) و بلیط سینما ۲۰ A$ (≈۱۳٫۱ $)"
                        },
                        new
                        {
                            Id = 2006L,
                            CountryId = 2L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در سه شهر بزرگ: ≈ ۲٬۷۴۳ A$ (≈۱٬۷۹۸ $)"
                        },
                        new
                        {
                            Id = 2007L,
                            CountryId = 2L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر بزرگ: ≈ ۵٬۲۶۸ A$ (≈۳٬۴۵۳ $)"
                        },
                        new
                        {
                            Id = 2008L,
                            CountryId = 2L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: حدود ۸۲٫۱۷ A$ (≈۵۳٫۹ $) در ماه"
                        },
                        new
                        {
                            Id = 3001L,
                            CountryId = 3L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۳٬۴۰۷٫۶ یورو ≈ ۳٬۹۵۲ $"
                        },
                        new
                        {
                            Id = 3002L,
                            CountryId = 3L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۹۸۵٫۶ یورو ≈ ۱٬۱۴۳ $"
                        },
                        new
                        {
                            Id = 3003L,
                            CountryId = 3L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه حدود ۵۸ € (≈۶۷٫۳ $)"
                        },
                        new
                        {
                            Id = 3004L,
                            CountryId = 3L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب و گاز برای آپارتمان ۸۵ مترمربع: حدود ۳۰۳٫۰۸ € (≈۳۵۱٫۶ $)"
                        },
                        new
                        {
                            Id = 3005L,
                            CountryId = 3L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ۳۵٫۴۲ € (≈۴۱٫۱ $) و بلیط سینما ۱۲ € (≈۱۳٫۹ $)"
                        },
                        new
                        {
                            Id = 3006L,
                            CountryId = 3L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در سه شهر بزرگ: ≈ ۱٬۲۹۹ € (≈۱٬۵۰۶ $)"
                        },
                        new
                        {
                            Id = 3007L,
                            CountryId = 3L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر بزرگ: ≈ ۲٬۴۴۵ € (≈۲٬۸۳۶ $)"
                        },
                        new
                        {
                            Id = 3008L,
                            CountryId = 3L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: حدود ۴۳٫۲۲ € (≈۵۰٫۱ $) در ماه"
                        },
                        new
                        {
                            Id = 4001L,
                            CountryId = 4L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۴٬۲۳۱٫۳ دلار آمریکا"
                        },
                        new
                        {
                            Id = 4002L,
                            CountryId = 4L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۱٬۱۷۳٫۴ دلار آمریکا"
                        },
                        new
                        {
                            Id = 4003L,
                            CountryId = 4L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه حمل‌ونقل عمومی حدود ۶۵ $"
                        },
                        new
                        {
                            Id = 4004L,
                            CountryId = 4L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب و گاز برای آپارتمان ۸۵ مترمربع: حدود ۲۱۰٫۳۷ $"
                        },
                        new
                        {
                            Id = 4005L,
                            CountryId = 4L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ۴۵٫۵۱ $ و بلیط سینما ۱۵ $"
                        },
                        new
                        {
                            Id = 4006L,
                            CountryId = 4L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در نیویورک، لس‌آنجلس و شیکاگو: ≈ ۳٬۰۷۲ $"
                        },
                        new
                        {
                            Id = 4007L,
                            CountryId = 4L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر: ≈ ۵٬۸۸۶ $"
                        },
                        new
                        {
                            Id = 4008L,
                            CountryId = 4L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: ۷۲٫۴۳ $ در ماه"
                        },
                        new
                        {
                            Id = 5001L,
                            CountryId = 5L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۳٬۶۲۱٫۸ یورو ≈ ۴٬۲۰۱ $"
                        },
                        new
                        {
                            Id = 5002L,
                            CountryId = 5L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۱٬۰۱۳٫۹ یورو ≈ ۱٬۱۷۶ $"
                        },
                        new
                        {
                            Id = 5003L,
                            CountryId = 5L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه ۹۰ € (≈۱۰۴٫۴ $)"
                        },
                        new
                        {
                            Id = 5004L,
                            CountryId = 5L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب و گاز: حدود ۲۲۶٫۷ € (≈۲۶۲٫۹ $)"
                        },
                        new
                        {
                            Id = 5005L,
                            CountryId = 5L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ۳۷٫۰۵ € (≈۴۳٫۰ $) و بلیط سینما ۱۴ € (≈۱۶٫۲ $)"
                        },
                        new
                        {
                            Id = 5006L,
                            CountryId = 5L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در آمستردام، روتردام و لاهه: ≈ ۱٬۷۰۲ € (≈۱٬۹۷۴ $)"
                        },
                        new
                        {
                            Id = 5007L,
                            CountryId = 5L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر: ≈ ۲٬۹۱۵ € (≈۳٬۳۸۲ $)"
                        },
                        new
                        {
                            Id = 5008L,
                            CountryId = 5L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: ۴۳٫۰۷ € (≈۵۰٫۰ $) در ماه"
                        },
                        new
                        {
                            Id = 6001L,
                            CountryId = 6L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۲٬۵۵۳٫۷ یورو ≈ ۲٬۹۶۲ $"
                        },
                        new
                        {
                            Id = 6002L,
                            CountryId = 6L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۷۰۶٫۷ یورو ≈ ۸۱۹٫۸ $"
                        },
                        new
                        {
                            Id = 6003L,
                            CountryId = 6L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه ۳۰ € (≈۳۴٫۸ $)"
                        },
                        new
                        {
                            Id = 6004L,
                            CountryId = 6L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب و گاز: حدود ۱۳۱٫۶۶ € (≈۱۵۲٫۷ $)"
                        },
                        new
                        {
                            Id = 6005L,
                            CountryId = 6L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ۴۰٫۶۶ € (≈۴۷٫۲ $) و بلیط سینما ۸ € (≈۹٫۳ $)"
                        },
                        new
                        {
                            Id = 6006L,
                            CountryId = 6L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در مادرید، بارسلونا و والنسیا: ≈ ۱٬۲۴۸ € (≈۱٬۴۴۷ $)"
                        },
                        new
                        {
                            Id = 6007L,
                            CountryId = 6L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر: ≈ ۲٬۰۸۱ € (≈۲٬۴۱۴ $)"
                        },
                        new
                        {
                            Id = 6008L,
                            CountryId = 6L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: حدود ۲۹٫۰۱ € (≈۳۳٫۷ $) در ماه"
                        },
                        new
                        {
                            Id = 7001L,
                            CountryId = 7L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۳۷٬۹۱۸٫۹ کرون سوئد ≈ ۴٬۰۱۲ دلار آمریکا"
                        },
                        new
                        {
                            Id = 7002L,
                            CountryId = 7L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۱۰٬۲۱۶٫۳ کرون ≈ ۱٬۰۸۱ دلار آمریکا"
                        },
                        new
                        {
                            Id = 7003L,
                            CountryId = 7L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه ۸۶۰ kr (≈۹۱٫۰ $)"
                        },
                        new
                        {
                            Id = 7004L,
                            CountryId = 7L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب و گاز: حدود ۱٬۲۴۱٫۵۸ kr (≈۱۳۱٫۴ $)"
                        },
                        new
                        {
                            Id = 7005L,
                            CountryId = 7L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ۳۹۵٫۱۲ kr (≈۴۱٫۸ $) و بلیط سینما ۱۵۹ kr (≈۱۶٫۸ $)"
                        },
                        new
                        {
                            Id = 7006L,
                            CountryId = 7L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در استکهلم، مالمو و گوتنبرگ: ≈ ۱۰٬۹۵۴ kr (≈۱٬۱۵۹ $)"
                        },
                        new
                        {
                            Id = 7007L,
                            CountryId = 7L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر: ≈ ۱۹٬۹۶۱ kr (≈۲٬۱۱۲ $)"
                        },
                        new
                        {
                            Id = 7008L,
                            CountryId = 7L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: ۳۷۷٫۶۳ kr (≈۴۰٫۰ $) در ماه"
                        },
                        new
                        {
                            Id = 8001L,
                            CountryId = 8L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۳٬۱۰۸٫۱ یورو ≈ ۳٬۶۰۵ $"
                        },
                        new
                        {
                            Id = 8002L,
                            CountryId = 8L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۸۶۹٫۷ یورو ≈ ۱٬۰۰۹ $"
                        },
                        new
                        {
                            Id = 8003L,
                            CountryId = 8L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه حدود ۳۸ € (≈۴۴٫۱ $)"
                        },
                        new
                        {
                            Id = 8004L,
                            CountryId = 8L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب، گاز و زباله برای آپارتمان ۸۵ مترمربع: حدود ۱۹۵٫۸۶ € (≈۲۲۷٫۲ $)"
                        },
                        new
                        {
                            Id = 8005L,
                            CountryId = 8L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ۴۹٫۳۴ € (≈۵۷٫۲ $) و بلیط سینما ۹ € (≈۱۰٫۴ $)"
                        },
                        new
                        {
                            Id = 8006L,
                            CountryId = 8L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در رم، میلان و ناپل: ≈ ۱٬۲۲۲ € (≈۱٬۴۱۷ $)"
                        },
                        new
                        {
                            Id = 8007L,
                            CountryId = 8L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر: ≈ ۲٬۳۶۹ € (≈۲٬۷۴۸ $)"
                        },
                        new
                        {
                            Id = 8008L,
                            CountryId = 8L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: ۲۷٫۱۸ € (≈۳۱٫۵ $) در ماه"
                        },
                        new
                        {
                            Id = 9001L,
                            CountryId = 9L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۱٬۰۲۲٫۵ ﷼ عمان ≈ ۲٬۶۵۵ دلار آمریکا"
                        },
                        new
                        {
                            Id = 9002L,
                            CountryId = 9L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۲۸۷٫۱ ﷼ عمان ≈ ۷۴۶ دلار آمریکا"
                        },
                        new
                        {
                            Id = 9003L,
                            CountryId = 9L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه ۲۵ ﷼ (≈۶۴٫۹ $)"
                        },
                        new
                        {
                            Id = 9004L,
                            CountryId = 9L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب و گاز: حدود ۳۸٫۸۸ ﷼ (≈۱۰۱٫۰ $)"
                        },
                        new
                        {
                            Id = 9005L,
                            CountryId = 9L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ۲۰٫۰۳ ﷼ (≈۵۲٫۰ $) و بلیط سینما ۴ ﷼ (≈۱۰٫۴ $)"
                        },
                        new
                        {
                            Id = 9006L,
                            CountryId = 9L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در مسقط، صلاله و صحار: ≈ ۱۶۱٫۳ ﷼ (≈۴۱۹ $)"
                        },
                        new
                        {
                            Id = 9007L,
                            CountryId = 9L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر: ≈ ۳۱۴٫۷ ﷼ (≈۸۱۷ $)"
                        },
                        new
                        {
                            Id = 9008L,
                            CountryId = 9L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: ۲۷٫۷۴ ﷼ (≈۷۲٫۰ $) در ماه"
                        },
                        new
                        {
                            Id = 10001L,
                            CountryId = 10L,
                            IsDeleted = false,
                            Type = 1,
                            Value = "هزینه ماهانه خانواده چهار نفره (بدون اجاره): ۹۸٬۷۷۹٫۵ روپیه ≈ ۱٬۱۰۵ دلار آمریکا"
                        },
                        new
                        {
                            Id = 10002L,
                            CountryId = 10L,
                            IsDeleted = false,
                            Type = 2,
                            Value = "هزینه ماهانه یک نفر (بدون اجاره): ۲۷٬۵۱۸٫۲ روپیه ≈ ۳۰۸ دلار آمریکا"
                        },
                        new
                        {
                            Id = 10003L,
                            CountryId = 10L,
                            IsDeleted = false,
                            Type = 3,
                            Value = "حمل‌ونقل: کارت ماهانه حمل‌ونقل عمومی حدود ۷۶۴ ₹ (≈۸٫۵ $)"
                        },
                        new
                        {
                            Id = 10004L,
                            CountryId = 10L,
                            IsDeleted = false,
                            Type = 4,
                            Value = "برق، آب و گاز برای آپارتمان ۸۵ مترمربع: حدود ۳٬۵۱۶٫۳۵ ₹ (≈۳۹٫۳ $)"
                        },
                        new
                        {
                            Id = 10005L,
                            CountryId = 10L,
                            IsDeleted = false,
                            Type = 5,
                            Value = "تفریح: عضویت باشگاه ۱٬۳۶۷٫۱۳ ₹ (≈۱۵٫۳ $) و بلیط سینما ۳۰۰ ₹ (≈۳٫۴ $)"
                        },
                        new
                        {
                            Id = 10006L,
                            CountryId = 10L,
                            IsDeleted = false,
                            Type = 6,
                            Value = "میانگین اجاره آپارتمان ۱ خوابه در بمبئی، دهلی و بنگلور: ≈ ۳۷٬۴۳۷ ₹ (≈۴۱۸٫۹ $)"
                        },
                        new
                        {
                            Id = 10007L,
                            CountryId = 10L,
                            IsDeleted = false,
                            Type = 7,
                            Value = "میانگین اجاره آپارتمان ۳ خوابه در سه شهر: ≈ ۱۰۰٬۱۲۵ ₹ (≈۱٬۱۲۰٫۴ $)"
                        },
                        new
                        {
                            Id = 10008L,
                            CountryId = 10L,
                            IsDeleted = false,
                            Type = 8,
                            Value = "اینترنت نامحدود: حدود ۶۸۴٫۶ ₹ (≈۷٫۷ $) در ماه"
                        });
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Countries.CountryRestriction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryRestrictions");

                    b.HasData(
                        new
                        {
                            Id = 101L,
                            CountryId = 1L,
                            Description = "بر اساس قانون مهاجرت کانادا، افرادی که به دلایل امنیتی، نقض حقوق بشر، جرایم یا تحت تحریم هستند ممکن است غیرقابل پذیرش شناخته شوند؛ در سال‌های اخیر رژیم ایران به عنوان ناقض حقوق بشر تحت قانون معرفی شده و برخی مقامات ارشد رژیم به همین دلیل از ورود به کانادا منع شده‌اند【129470507908352†L44-L61】【129470507908352†L107-L124】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 102L,
                            CountryId = 1L,
                            Description = "ادارهٔ مهاجرت کانادا تأکید می‌کند که همهٔ متقاضیان ایرانی باید معیارهای پذیرش از جمله قانون‌مداری، سلامت، عدم خطر امنیتی و داشتن تمکن مالی کافی را رعایت کنند و تنها در صورت تأمین این شرایط می‌توانند وضعیت اقامت خود را تمدید کنند【923856638287588†L55-L175】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 201L,
                            CountryId = 2L,
                            Description = "سایت رسمی وزارت کشور استرالیا اعلام کرده که به دلیل تعطیلی موقت سفارت این کشور در تهران، ایرانیان باید درخواست‌های ویزا را به صورت آنلاین ارائه دهند؛ درخواست‌ها بر اساس معیارهای سلامت، شخصیت و امنیتی ارزیابی می‌شود و ممکن است به ارائهٔ بیومتریک نیاز باشد【65972592913445†L149-L187】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 202L,
                            CountryId = 2L,
                            Description = "با وجود عدم ممنوعیت رسمی برای ایرانیان، فرایند بررسی ویزا ممکن است به دلیل بررسی‌های امنیتی طولانی‌تر شود و متقاضیان باید مدارک کاملی مانند گواهی عدم سوءپیشینه، آزمایش‌های پزشکی و اسناد مالی ارائه دهند.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 301L,
                            CountryId = 3L,
                            Description = "به‌دلیل کاهش ظرفیت سفارت آلمان در تهران، وقت‌دهی برای ویزاهای کاری و تخصصی بسیار محدود شده و پرونده‌های ایرانیان با تأخیر طولانی بررسی می‌شوند؛ اولویت به ویزاهای خانوادگی و انسان‌دوستانه داده می‌شود【974668712062734†L41-L63】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 302L,
                            CountryId = 3L,
                            Description = "برای دریافت اجازهٔ اقامت خوداشتغالی، متقاضیان باید طرح تجاری معتبر، تضمین مالی و مدارک امنیتی ارائه دهند؛ عدم ارائهٔ این مدارک می‌تواند منجر به رد درخواست شود【496840517904274†L302-L313】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 401L,
                            CountryId = 4L,
                            Description = "یک فرمان ریاست‌جمهوری ایالات متحده در ۴ ژوئن ۲۰۲۵ ورود اتباع ایران را به عنوان مهاجر و غیرمهاجر به‌دلیل نگرانی‌های امنیتی و حمایت دولتی از تروریسم تعلیق کرده است【652412899581844†L326-L335】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 402L,
                            CountryId = 4L,
                            Description = "خدمت یا عضویت در سپاه پاسداران انقلاب اسلامی می‌تواند موجب عدم واجد شرایط بودن برای ویزا یا ورود به آمریکا شود و برای ویزاهای مهاجرتی هیچ بخشودگی وجود ندارد【594094986034718†L369-L385】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 403L,
                            CountryId = 4L,
                            Description = "متقاضیان ایرانی باید در مصاحبهٔ حضوری و مراحل بررسی اداری شرکت کنند و ممکن است به دلیل بررسی‌های امنیتی، روند پردازش ویزا طولانی‌تر باشد【594094986034718†L288-L329】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 501L,
                            CountryId = 5L,
                            Description = "سفارت هلند در تهران به‌دلیل وضعیت امنیتی تنها خدمات محدودی مانند دریافت استیکر MVV، آزمون هم‌پیوندی و گذرنامه ارائه می‌دهد و وقت‌ها بسیار محدود است؛ این شرایط موجب تاخیر در رسیدگی به درخواست‌های ایرانیان می‌شود【244439518350853†L95-L104】【244439518350853†L184-L188】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 502L,
                            CountryId = 5L,
                            Description = "در مرکز VFS Global تهران امکان درخواست ویزای گردشگری برای هلند وجود ندارد و فقط درخواست‌های خاص مانند دیدار خانواده و تجارت پذیرفته می‌شود【348312902467940†L40-L42】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 601L,
                            CountryId = 6L,
                            Description = "برنامهٔ ویزای سرمایه‌گذاری اسپانیا (گلدن ویزا) در آوریل ۲۰۲۵ لغو شد و بنابراین مسیر سرمایه‌گذاری برای اتباع خارجی از جمله ایرانیان بسته شده است【810607001739387†L84-L124】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 602L,
                            CountryId = 6L,
                            Description = "سایت مرکز خدمات ویزای اسپانیا در ایران هشدار می‌دهد که وقت‌های ویزا باید فقط از طریق سایت رسمی رزرو شود و پرداخت به دلالان ممنوع است؛ عدم رعایت این موارد می‌تواند باعث مسدود شدن دسترسی به وقت‌ها شود【791952424432128†L124-L172】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 701L,
                            CountryId = 7L,
                            Description = "سفارت سوئد در تهران اعلام کرده که متقاضیان ایرانی باید مدارک کامل شامل گذرنامه، فرم درخواست، اثر انگشت، هدف سفر، محل اقامت و تمکن مالی را ارائه کنند و در صورت نقص مدارک، درخواست پذیرفته نمی‌شود【473232319044766†L151-L182】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 702L,
                            CountryId = 7L,
                            Description = "به دلیل حجم بالای درخواست‌ها و ضرورت ثبت بیومتریک، زمان انتظار برای صدور ویزاهای سوئد برای ایرانیان ممکن است طولانی شود و متقاضیان باید زودتر از موعد برنامه‌ریزی کنند.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 801L,
                            CountryId = 8L,
                            Description = "سفارت ایتالیا در تهران در ۲۴ ژوئن ۲۰۲۵ به دلیل شرایط امنیتی، خدمات کنسولی خود را به طور موقت به حالت تعلیق درآورد؛ این وضعیت باعث محدود شدن دسترسی و افزایش تأخیر در بررسی ویزاها شده و در حال حاضر تمرکز بر پرونده‌های دانشجویان ایرانی پذیرفته‌شده است【22804495354170†L179-L190】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 802L,
                            CountryId = 8L,
                            Description = "به دلیل تعلیق خدمات در تهران، متقاضیان ایرانی ممکن است مجبور شوند از طریق سایر سفارت‌های ایتالیا در منطقه درخواست دهند و انتظار برای دریافت وقت سفارت و پردازش ویزا طولانی‌تر است.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 901L,
                            CountryId = 9L,
                            Description = "برای دریافت اقامت سرمایه‌گذاری عمان، متقاضی باید حداقل ۲۰۰٬۰۰۰ ریال عمانی سرمایه‌گذاری کند و از طریق وزارت تجارت درخواست دهد؛ همچنین سن متقاضی باید حداقل ۲۱ سال باشد و گواهی عدم سوءپیشینه ارائه دهد【309023576662590†L44-L98】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 902L,
                            CountryId = 9L,
                            Description = "عمان ورود گردشگران ایرانی را بدون ویزا تا ۱۰ روز مجاز کرده است، اما مسافران باید رزرو هتل، بیمه درمانی و بلیط برگشت داشته باشند؛ عدم رعایت این شرایط موجب جریمهٔ روزانه می‌شود【237265316935786†L33-L43】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 1001L,
                            CountryId = 10L,
                            Description = "اتباع ایرانی باید درخواست ویزای هند را به‌صورت آنلاین تکمیل کنند و سپس نسخهٔ چاپی فرم را همراه با پاسپورت و مدارک لازم به مرکز درخواست کنسولی هند در ایران (ICAC) تحویل دهند؛ فرم‌ها باید به زبان انگلیسی تکمیل شوند و فرم‌های ناقص یا دارای اطلاعات غلط توسط مرکز یا سفارت رد می‌شوند【909243431442982†L692-L706】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 1002L,
                            CountryId = 10L,
                            Description = "هر درخواست ویزا به‌صورت موردی بررسی می‌شود و سفارت ممکن است در هر مرحله از روند بررسی اطلاعات اضافی مطالبه کند که می‌تواند زمان پردازش را افزایش دهد؛ ارائهٔ درخواست و پرداخت هزینه تضمینی برای دریافت ویزا نیست و درخواست صدور زودتر ویزا پذیرفته نمی‌شود【909243431442982†L705-L715】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 1003L,
                            CountryId = 10L,
                            Description = "زمان صدور ویزا بسته به نوع ویزا متفاوت است: ویزای تجاری معمولاً طی ۳ روز کاری، ویزای توریستی و کنفرانس طی ۴ روز کاری و سایر ویزاها (از جمله پژوهشی) برای متقاضیان دارای ملیت ایرانی در صورت تکمیل مدارک طی ۷ روز کاری صادر می‌شود【909243431442982†L719-L723】.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 1004L,
                            CountryId = 10L,
                            Description = "برای دریافت اقامت دائم سرمایه‌گذار، متقاضیان باید دست‌کم ۱۰ کرور روپیه ظرف ۱۸ ماه یا ۲۵ کرور روپیه ظرف ۳۶ ماه سرمایه‌گذاری کنند و حداقل ۲۰ شغل ایجاد کنند【147254951936675†screenshot】. این شرط سرمایه‌گذاری برای بسیاری از ایرانیان بسیار بالا است و یکی از موانع مهم محسوب می‌شود.",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubscriptionEndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionPlanId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("SubscriptionStartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedEvaluations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Customers.ImmigrationEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int>("DegreeLevel")
                        .HasColumnType("int");

                    b.Property<int>("FieldCategory")
                        .HasColumnType("int");

                    b.Property<decimal>("InvestmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobCategory")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LanguageCertificate")
                        .HasColumnType("int");

                    b.Property<int>("MBTIPersonality")
                        .HasColumnType("int");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("WillingToStudy")
                        .HasColumnType("bit");

                    b.Property<int>("WorkExperienceYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CustomerId");

                    b.ToTable("ImmigrationEvaluations");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Payments.PaymentRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CallbackUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("GatewayTrackId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PlanId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GatewayTrackId");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("PaymentRequests");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Payments.PaymentResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayTrackId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("PaymentRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ResultCode")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRequestId");

                    b.ToTable("PaymentResponses");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Permissions.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Permissions.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Users.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Blogs.ArticleComment", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Blogs.Article", "Article")
                        .WithMany("ArticleComment")
                        .HasForeignKey("ArticleId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chamedoon.Domin.Entity.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Countries.CountryLivingCost", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Countries.Country", "Country")
                        .WithMany("LivingCosts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Countries.CountryRestriction", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Countries.Country", "Country")
                        .WithMany("Restrictions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Customers.Customer", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Users.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("Chamedoon.Domin.Entity.Customers.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Customers.ImmigrationEvaluation", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Customers.Customer", "Customer")
                        .WithMany("ImmigrationEvaluations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Payments.PaymentRequest", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Customers.Customer", "Customer")
                        .WithMany("PaymentRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Payments.PaymentResponse", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Payments.PaymentRequest", "PaymentRequest")
                        .WithMany("Responses")
                        .HasForeignKey("PaymentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentRequest");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Permissions.RolePermission", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Permissions.RolePermission", null)
                        .WithMany("Permissions")
                        .HasForeignKey("ParentId");

                    b.HasOne("Chamedoon.Domin.Entity.Permissions.Role", "Roles")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Users.UserRole", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Permissions.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chamedoon.Domin.Entity.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Permissions.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Chamedoon.Domin.Entity.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Blogs.Article", b =>
                {
                    b.Navigation("ArticleComment");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Countries.Country", b =>
                {
                    b.Navigation("LivingCosts");

                    b.Navigation("Restrictions");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Customers.Customer", b =>
                {
                    b.Navigation("ImmigrationEvaluations");

                    b.Navigation("PaymentRequests");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Payments.PaymentRequest", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Permissions.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Permissions.RolePermission", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Chamedoon.Domin.Entity.Users.User", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
